In [1]:
import numpy as np
import math

In [2]:
def basic_sigmoid(x):
    """
    x: a real number
    return: sigmoid(x)
    """
    s = 1 / (1 + math.exp(-x))
    return s

In [3]:
print(basic_sigmoid(1))

0.7310585786300049


In [4]:
def sigmoid(x):
    """
    x: scalar or numpy array
    return: sigmoid(x), same shape as x
    """
    s = 1 / (1 + np.exp(-x))
    return s

In [5]:
X = np.array([1, 2, 3])
print(sigmoid(X))

[0.73105858 0.88079708 0.95257413]


In [6]:
def sigmoid_derivative(x):
    """
    x: scalar or numpy array
    return: gradient of sigmoid at x
    """
    s = sigmoid(x)
    ds = s * (1 - s)
    return ds

In [7]:
x = np.array([1, 2, 3])
print(sigmoid_derivative(x))

[0.19661193 0.10499359 0.04517666]


In [8]:
def image2vector(image):
    """
    image: numpy array of shape (length, height, depth)
    return: vector of shape (length*height*depth, 1)
    """
    v = image.reshape(-1, 1)
    return v

In [9]:
image = np.array([[[0.67, 0.03], [0.34, 0.61], [0.22, 0.35]],
                   [[0.72, 0.14], [0.83, 0.99], [0.60, 0.42]],
                   [[0.19, 0.51], [0.28, 0.13], [0.44, 0.90]]])
print(image2vector(image).shape)

(18, 1)


In [10]:
def normalize_rows(x):
    """
    x: numpy matrix of shape (n, m)
    return: normalized version of x, same shape
    """
    x_norm = np.linalg.norm(x, axis=1, keepdims=True)
    x = x / x_norm
    return x

In [11]:
x = np.array([[0, 3, 4], [1, 6, 4]])
print(normalize_rows(x))

[[0.         0.6        0.8       ]
 [0.13736056 0.82416338 0.54944226]]


In [12]:
def softmax(x):
    """
    x: numpy matrix of shape (n, m)
    return: softmax(x), same shape as x
    """
    x_exp = np.exp(x)
    x_sum = np.sum(x_exp, axis=1, keepdims=True)
    s = x_exp / x_sum 
    return s

In [13]:
x = np.array([[9, 2, 5, 0, 0], [7, 5, 0, 0, 0]])
print(softmax(x))

[[9.80897665e-01 8.94462891e-04 1.79657674e-02 1.21052389e-04
  1.21052389e-04]
 [8.78679856e-01 1.18916387e-01 8.01252314e-04 8.01252314e-04
  8.01252314e-04]]


In [14]:
def L1(yhat, y):
    """
    yhat: predicted labels, shape (m,)
    y: true labels, shape (m,)
    return: L1 loss
    """
    loss = np.sum(np.abs(y - yhat))
    return loss

In [15]:
yhat = np.array([.9, 0.2, 0.1, .4, .9])
y = np.array([1, 0, 0, 1, 1])
print(L1(yhat, y))

1.1


In [16]:
def L2(yhat, y):
    """
    yhat: predicted labels, shape (m,)
    y: true labels, shape (m,)
    return: L2 loss
    """
    diff = y - yhat
    loss = np.dot(diff, diff)
    return loss

In [17]:
yhat = np.array([.9, 0.2, 0.1, .4, .9])
y = np.array([1, 0, 0, 1, 1])
print(L2(yhat, y))

0.43
