In [1]:
import numpy as np
import matplotlib.pyplot as plt
import copy
%matplotlib inline
plt.rcParams['figure.figsize'] = (5.0, 4.0)
plt.rcParams['image.interpolation'] = 'nearest'
plt.rcParams['image.cmap'] = 'gray'
%load_ext autoreload
%autoreload 2

np.random.seed(1)

In [11]:
def sigmoid(Z):
    """
    Sigmoid activation.

    Arguments:
    Z -- numpy array of any shape

    Returns:
    A -- output of sigmoid(Z), same shape as Z
    cache -- Z, stored for computing the backward pass efficiently
    """
    A = 1 / (1 + np.exp(-Z))
    cache = Z
    return A, cache


def relu(Z):
    """
    ReLU activation.

    Arguments:
    Z -- numpy array of any shape

    Returns:
    A -- output of relu(Z), same shape as Z
    cache -- Z, stored for computing the backward pass efficiently
    """
    A = np.maximum(0, Z)
    cache = Z
    return A, cache


def sigmoid_backward(dA, cache):
    """
    Backward pass for a single SIGMOID unit.

    Arguments:
    dA -- post-activation gradient, of any shape
    cache -- Z stored from the forward pass

    Returns:
    dZ -- gradient of the cost with respect to Z
    """
    Z = cache
    s = 1 / (1 + np.exp(-Z))
    dZ = dA * s * (1 - s)
    return dZ


def relu_backward(dA, cache):
    """
    Backward pass for a single RELU unit.

    Arguments:
    dA -- post-activation gradient, of any shape
    cache -- Z stored from the forward pass

    Returns:
    dZ -- gradient of the cost with respect to Z
    """
    Z = cache
    dZ = np.array(dA, copy=True)
    dZ[Z <= 0] = 0
    return dZ

In [2]:
# GRADED FUNCTION: initialize_parameters

def initialize_parameters(n_x, n_h, n_y):
    """
    Argument:
    n_x -- size of the input layer
    n_h -- size of the hidden layer
    n_y -- size of the output layer
    
    Returns:
    parameters -- python dictionary containing your parameters:
                    W1 -- weight matrix of shape (n_h, n_x)
                    b1 -- bias vector of shape (n_h, 1)
                    W2 -- weight matrix of shape (n_y, n_h)
                    b2 -- bias vector of shape (n_y, 1)
    """
    
    np.random.seed(1)
    
    #(≈ 4 lines of code)
    # W1 = ...
    # b1 = ...
    # W2 = ...
    # b2 = ...
    # YOUR CODE STARTS HERE
    W1 = np.random.randn(n_h, n_x) * 0.01
    b1 = np.zeros((n_h, 1))
    W2 = np.random.randn(n_y, n_h) * 0.01
    b2 = np.zeros((n_y, 1))
    
    # YOUR CODE ENDS HERE
    
    parameters = {"W1": W1,
                  "b1": b1,
                  "W2": W2,
                  "b2": b2}
    
    return parameters    

In [4]:
print("Test Case 1:\n")
parameters = initialize_parameters(3, 2, 1)
print("W1 = " + str(parameters["W1"]))
print("b1 = " + str(parameters["b1"]))
print("W2 = " + str(parameters["W2"]))
print("b2 = " + str(parameters["b2"]))

assert parameters["W1"].shape == (2, 3)
assert parameters["b1"].shape == (2, 1)
assert parameters["W2"].shape == (1, 2)
assert parameters["b2"].shape == (1, 1)
assert np.all(parameters["b1"] == 0)
assert np.all(parameters["b2"] == 0)
print("\nAll tests passed.")

Test Case 1:

W1 = [[ 0.01624345 -0.00611756 -0.00528172]
 [-0.01072969  0.00865408 -0.02301539]]
b1 = [[0.]
 [0.]]
W2 = [[ 0.01744812 -0.00761207]]
b2 = [[0.]]

All tests passed.


In [5]:
# GRADED FUNCTION: initialize_parameters_deep

def initialize_parameters_deep(layer_dims):
    """
    Arguments:
    layer_dims -- python array (list) containing the dimensions of each layer in our network
    
    Returns:
    parameters -- python dictionary containing your parameters "W1", "b1", ..., "WL", "bL":
                    Wl -- weight matrix of shape (layer_dims[l], layer_dims[l-1])
                    bl -- bias vector of shape (layer_dims[l], 1)
    """
    
    np.random.seed(3)
    parameters = {}
    L = len(layer_dims) # number of layers in the network

    for l in range(1, L):
        #(≈ 2 lines of code)
        # parameters['W' + str(l)] = ...
        # parameters['b' + str(l)] = ...
        # YOUR CODE STARTS HERE
        parameters['W' + str(l)] = np.random.randn(layer_dims[l], layer_dims[l-1]) * 0.01
        parameters['b' + str(l)] = np.zeros((layer_dims[l], 1))
        
        # YOUR CODE ENDS HERE
        
        assert(parameters['W' + str(l)].shape == (layer_dims[l], layer_dims[l - 1]))
        assert(parameters['b' + str(l)].shape == (layer_dims[l], 1))

        
    return parameters

In [6]:
print("Test Case 1:\n")
parameters = initialize_parameters_deep([5, 4, 3])
print("W1 = " + str(parameters["W1"]))
print("b1 = " + str(parameters["b1"]))
print("W2 = " + str(parameters["W2"]))
print("b2 = " + str(parameters["b2"]))

assert parameters["W1"].shape == (4, 5)
assert parameters["b1"].shape == (4, 1)
assert parameters["W2"].shape == (3, 4)
assert parameters["b2"].shape == (3, 1)
assert np.all(parameters["b1"] == 0)
assert np.all(parameters["b2"] == 0)

print("\033[90m\nTest Case 2:\n")
layer_dims = [4, 3, 2, 1]
deep_params = initialize_parameters_deep(layer_dims)
assert len(deep_params) == 2 * (len(layer_dims) - 1)
for l in range(1, len(layer_dims)):
    assert deep_params["W" + str(l)].shape == (layer_dims[l], layer_dims[l-1])
    assert deep_params["b" + str(l)].shape == (layer_dims[l], 1)
    print(f"W{l} shape: {deep_params['W'+str(l)].shape}, b{l} shape: {deep_params['b'+str(l)].shape}")

print("\nAll tests passed.")

Test Case 1:

W1 = [[ 0.01788628  0.0043651   0.00096497 -0.01863493 -0.00277388]
 [-0.00354759 -0.00082741 -0.00627001 -0.00043818 -0.00477218]
 [-0.01313865  0.00884622  0.00881318  0.01709573  0.00050034]
 [-0.00404677 -0.0054536  -0.01546477  0.00982367 -0.01101068]]
b1 = [[0.]
 [0.]
 [0.]
 [0.]]
W2 = [[-0.01185047 -0.0020565   0.01486148  0.00236716]
 [-0.01023785 -0.00712993  0.00625245 -0.00160513]
 [-0.00768836 -0.00230031  0.00745056  0.01976111]]
b2 = [[0.]
 [0.]
 [0.]]

Test Case 2:

W1 shape: (3, 4), b1 shape: (3, 1)
W2 shape: (2, 3), b2 shape: (2, 1)
W3 shape: (1, 2), b3 shape: (1, 1)

All tests passed.


In [7]:
# GRADED FUNCTION: linear_forward

def linear_forward(A, W, b):
    """
    Implement the linear part of a layer's forward propagation.

    Arguments:
    A -- activations from previous layer (or input data): (size of previous layer, number of examples)
    W -- weights matrix: numpy array of shape (size of current layer, size of previous layer)
    b -- bias vector, numpy array of shape (size of the current layer, 1)

    Returns:
    Z -- the input of the activation function, also called pre-activation parameter 
    cache -- a python tuple containing "A", "W" and "b" ; stored for computing the backward pass efficiently
    """
    
    #(≈ 1 line of code)
    # Z = ...
    # YOUR CODE STARTS HERE
    Z = np.dot(W, A) + b
    
    # YOUR CODE ENDS HERE
    cache = (A, W, b)
    
    return Z, cache

In [8]:
print("Test Case 1:\n")
np.random.seed(1)
A_test = np.random.randn(3, 2)
W_test = np.random.randn(1, 3)
b_test = np.random.randn(1, 1)

Z, linear_cache = linear_forward(A_test, W_test, b_test)
print("Z = " + str(Z))

Z_expected = np.dot(W_test, A_test) + b_test
assert np.allclose(Z, Z_expected)
assert Z.shape == (1, 2)
assert linear_cache[0] is A_test
assert linear_cache[1] is W_test
assert linear_cache[2] is b_test

print("\nAll tests passed.")

Test Case 1:

Z = [[ 3.26295337 -1.23429987]]

All tests passed.


In [12]:
# GRADED FUNCTION: linear_activation_forward

def linear_activation_forward(A_prev, W, b, activation):
    """
    Implement the forward propagation for the LINEAR->ACTIVATION layer

    Arguments:
    A_prev -- activations from previous layer (or input data): (size of previous layer, number of examples)
    W -- weights matrix: numpy array of shape (size of current layer, size of previous layer)
    b -- bias vector, numpy array of shape (size of the current layer, 1)
    activation -- the activation to be used in this layer, stored as a text string: "sigmoid" or "relu"

    Returns:
    A -- the output of the activation function, also called the post-activation value 
    cache -- a python tuple containing "linear_cache" and "activation_cache";
             stored for computing the backward pass efficiently
    """
    
    if activation == "sigmoid":
        #(≈ 2 lines of code)
        # Z, linear_cache = ...
        # A, activation_cache = ...
        # YOUR CODE STARTS HERE
        Z, linear_cache = linear_forward(A_prev, W, b)
        A, activation_cache = sigmoid(Z) 
        
        # YOUR CODE ENDS HERE
    
    elif activation == "relu":
        #(≈ 2 lines of code)
        # Z, linear_cache = ...
        # A, activation_cache = ...
        # YOUR CODE STARTS HERE
        Z, linear_cache = linear_forward(A_prev, W, b)
        A, activation_cache = relu(Z)
        
        # YOUR CODE ENDS HERE
    cache = (linear_cache, activation_cache)

    return A, cache

In [13]:
print("Test Case 1: sigmoid\n")
np.random.seed(2)
A_prev_test = np.random.randn(3, 2)
W_test = np.random.randn(1, 3)
b_test = np.random.randn(1, 1)

A_sigmoid, sigmoid_cache = linear_activation_forward(A_prev_test, W_test, b_test, activation="sigmoid")
print("With sigmoid: A = " + str(A_sigmoid))
assert np.all((A_sigmoid >= 0) & (A_sigmoid <= 1))

print("\033[90m\nTest Case 2: relu\n")
A_relu, relu_cache = linear_activation_forward(A_prev_test, W_test, b_test, activation="relu")
print("With ReLU: A = " + str(A_relu))
assert np.all(A_relu >= 0)

Z_expected = np.dot(W_test, A_prev_test) + b_test
assert np.allclose(A_sigmoid, 1 / (1 + np.exp(-Z_expected)))
assert np.allclose(A_relu, np.maximum(0, Z_expected))

print("\nAll tests passed.")

Test Case 1: sigmoid

With sigmoid: A = [[0.96890023 0.11013289]]

Test Case 2: relu

With ReLU: A = [[3.43896131 0.        ]]

All tests passed.


In [14]:
# GRADED FUNCTION: L_model_forward

def L_model_forward(X, parameters):
    """
    Implement forward propagation for the [LINEAR->RELU]*(L-1)->LINEAR->SIGMOID computation
    
    Arguments:
    X -- data, numpy array of shape (input size, number of examples)
    parameters -- output of initialize_parameters_deep()
    
    Returns:
    AL -- activation value from the output (last) layer
    caches -- list of caches containing:
                every cache of linear_activation_forward() (there are L of them, indexed from 0 to L-1)
    """

    caches = []
    A = X
    L = len(parameters) // 2                  # number of layers in the neural network
    
    # Implement [LINEAR -> RELU]*(L-1). Add "cache" to the "caches" list.
    # The for loop starts at 1 because layer 0 is the input
    for l in range(1, L):
        A_prev = A 
        #(≈ 2 lines of code)
        # A, cache = ...
        # caches ...
        # YOUR CODE STARTS HERE
        A, cache = linear_activation_forward(A_prev, parameters['W' + str(l)], parameters['b' + str(l)], activation="relu")
        caches.append(cache)
        
        # YOUR CODE ENDS HERE
    
    # Implement LINEAR -> SIGMOID. Add "cache" to the "caches" list.
    #(≈ 2 lines of code)
    # AL, cache = ...
    # caches ...
    # YOUR CODE STARTS HERE
    AL, cache = linear_activation_forward(A, parameters['W' + str(L)], parameters['b' + str(L)], activation="sigmoid")
    caches.append(cache)
    
    # YOUR CODE ENDS HERE
          
    return AL, caches

In [15]:
print("Test Case 1:\n")
np.random.seed(6)
X_test = np.random.randn(5, 4)
parameters_test = initialize_parameters_deep([5, 4, 3, 1])

AL, caches = L_model_forward(X_test, parameters_test)
print("AL = " + str(AL))
print("Length of caches list = " + str(len(caches)))

assert AL.shape == (1, 4)
assert np.all((AL >= 0) & (AL <= 1))
assert len(caches) == len(parameters_test) // 2

print("\nAll tests passed.")

Test Case 1:

AL = [[0.5        0.49999832 0.49999821 0.49999955]]
Length of caches list = 3

All tests passed.


In [16]:
# GRADED FUNCTION: compute_cost

def compute_cost(AL, Y):
    """
    Implement the cost function defined by equation (7).

    Arguments:
    AL -- probability vector corresponding to your label predictions, shape (1, number of examples)
    Y -- true "label" vector (for example: containing 0 if non-cat, 1 if cat), shape (1, number of examples)

    Returns:
    cost -- cross-entropy cost
    """
    
    m = Y.shape[1]

    # Compute loss from aL and y.
    # (≈ 1 lines of code)
    # cost = ...
    # YOUR CODE STARTS HERE
    cost = -(1/m) * np.sum(Y * np.log(AL) + (1 - Y) * np.log(1 - AL))
    
    # YOUR CODE ENDS HERE
    
    cost = np.squeeze(cost)      # To make sure your cost's shape is what we expect (e.g. this turns [[17]] into 17).

    
    return cost

In [17]:
print("Test Case 1:\n")
Y_test = np.asarray([[1, 1, 1]])
AL_test = np.array([[0.8, 0.9, 0.4]])

cost = compute_cost(AL_test, Y_test)
print("cost = " + str(cost))

expected_cost = -np.mean(Y_test * np.log(AL_test) + (1 - Y_test) * np.log(1 - AL_test))
assert np.isclose(cost, expected_cost)
assert cost.shape == ()

print("\033[90m\nTest Case 2: near-perfect prediction should give near-zero cost\n")
Y_perfect = np.array([[1, 0, 1]])
AL_perfect = np.array([[1 - 1e-9, 1e-9, 1 - 1e-9]])
cost_perfect = compute_cost(AL_perfect, Y_perfect)
print("cost = " + str(cost_perfect))
assert cost_perfect < 1e-6

print("\nAll tests passed.")

Test Case 1:

cost = 0.41493159961539694

Test Case 2: near-perfect prediction should give near-zero cost

cost = 9.999999722180686e-10

All tests passed.


In [18]:
A = np.array([[1, 2], [3, 4]])

print('axis=1 and keepdims=True')
print(np.sum(A, axis=1, keepdims=True))
print('axis=1 and keepdims=False')
print(np.sum(A, axis=1, keepdims=False))
print('axis=0 and keepdims=True')
print(np.sum(A, axis=0, keepdims=True))
print('axis=0 and keepdims=False')
print(np.sum(A, axis=0, keepdims=False))

axis=1 and keepdims=True
[[3]
 [7]]
axis=1 and keepdims=False
[3 7]
axis=0 and keepdims=True
[[4 6]]
axis=0 and keepdims=False
[4 6]


In [19]:
# GRADED FUNCTION: linear_backward

def linear_backward(dZ, cache):
    """
    Implement the linear portion of backward propagation for a single layer (layer l)

    Arguments:
    dZ -- Gradient of the cost with respect to the linear output (of current layer l)
    cache -- tuple of values (A_prev, W, b) coming from the forward propagation in the current layer

    Returns:
    dA_prev -- Gradient of the cost with respect to the activation (of the previous layer l-1), same shape as A_prev
    dW -- Gradient of the cost with respect to W (current layer l), same shape as W
    db -- Gradient of the cost with respect to b (current layer l), same shape as b
    """
    A_prev, W, b = cache
    m = A_prev.shape[1]

    ### START CODE HERE ### (≈ 3 lines of code)
    # dW = ...
    # db = ... sum by the rows of dZ with keepdims=True
    # dA_prev = ...
    # YOUR CODE STARTS HERE
    dW = (1/m) * np.dot(dZ, A_prev.T)
    db = (1/m) * np.sum(dZ, axis=1, keepdims=True)
    dA_prev = np.dot(W.T, dZ)
    
    # YOUR CODE ENDS HERE
    
    return dA_prev, dW, db

In [20]:
print("Test Case 1:\n")
np.random.seed(1)
A_prev_test = np.random.randn(3, 4)
W_test = np.random.randn(2, 3)
b_test = np.random.randn(2, 1)
dZ_test = np.random.randn(2, 4)

linear_cache_test = (A_prev_test, W_test, b_test)
dA_prev, dW, db = linear_backward(dZ_test, linear_cache_test)

print("dA_prev = " + str(dA_prev))
print("dW = " + str(dW))
print("db = " + str(db))

assert dA_prev.shape == A_prev_test.shape
assert dW.shape == W_test.shape
assert db.shape == b_test.shape

# Numerical gradient check (finite differences) as an independent sanity check
def numerical_gradient_linear(A_prev, W, b, dZ, param_name, epsilon=1e-7):
    m = A_prev.shape[1]
    if param_name == "A_prev":
        base, scale = A_prev, 1.0
    elif param_name == "W":
        base, scale = W, 1.0/m
    else:
        base, scale = b, 1.0/m
    grad = np.zeros_like(base)
    it = np.nditer(base, flags=["multi_index"])
    while not it.finished:
        idx = it.multi_index
        orig = base[idx]
        base[idx] = orig + epsilon
        Z_plus, _ = linear_forward(A_prev, W, b)
        base[idx] = orig - epsilon
        Z_minus, _ = linear_forward(A_prev, W, b)
        base[idx] = orig
        grad[idx] = scale * np.sum(dZ * (Z_plus - Z_minus)) / (2*epsilon)
        it.iternext()
    return grad

dW_numeric = numerical_gradient_linear(A_prev_test, W_test, b_test, dZ_test, "W")
db_numeric = numerical_gradient_linear(A_prev_test, W_test, b_test, dZ_test, "b")
dA_numeric = numerical_gradient_linear(A_prev_test, W_test, b_test, dZ_test, "A_prev")

assert np.allclose(dW, dW_numeric, atol=1e-6)
assert np.allclose(db, db_numeric, atol=1e-6)
assert np.allclose(dA_prev, dA_numeric, atol=1e-6)

print("\nAll tests passed (gradients match numerical approximation).")

Test Case 1:

dA_prev = [[-0.63598503  0.38294768 -0.15552247  0.86723181]
 [ 0.26736461 -0.32174216 -0.3250701  -0.03163209]
 [-2.03867237  1.89806902  1.13007623  1.3911858 ]]
dW = [[-0.87585828 -0.59912655 -0.08839671]
 [ 0.73763362  0.71278189  0.55151192]]
db = [[ 0.3620474 ]
 [-0.21038289]]

All tests passed (gradients match numerical approximation).


In [21]:
# GRADED FUNCTION: linear_activation_backward

def linear_activation_backward(dA, cache, activation):
    """
    Implement the backward propagation for the LINEAR->ACTIVATION layer.
    
    Arguments:
    dA -- post-activation gradient for current layer l 
    cache -- tuple of values (linear_cache, activation_cache) we store for computing backward propagation efficiently
    activation -- the activation to be used in this layer, stored as a text string: "sigmoid" or "relu"
    
    Returns:
    dA_prev -- Gradient of the cost with respect to the activation (of the previous layer l-1), same shape as A_prev
    dW -- Gradient of the cost with respect to W (current layer l), same shape as W
    db -- Gradient of the cost with respect to b (current layer l), same shape as b
    """
    linear_cache, activation_cache = cache
    
    if activation == "relu":
        #(≈ 2 lines of code)
        # dZ =  ...
        # dA_prev, dW, db =  ...
        # YOUR CODE STARTS HERE
        dZ = relu_backward(dA, activation_cache)
        dA_prev, dW, db = linear_backward(dZ, linear_cache)
        
        # YOUR CODE ENDS HERE
        
    elif activation == "sigmoid":
        #(≈ 2 lines of code)
        # dZ =  ...
        # dA_prev, dW, db =  ...
        # YOUR CODE STARTS HERE
        dZ = sigmoid_backward(dA, activation_cache)
        dA_prev, dW, db = linear_backward(dZ, linear_cache)
        
        # YOUR CODE ENDS HERE
    
    return dA_prev, dW, db

In [22]:
print("Test Case 1: sigmoid\n")
np.random.seed(2)
dA_test = np.random.randn(1, 2)
A_prev_test = np.random.randn(3, 2)
W_test = np.random.randn(1, 3)
b_test = np.random.randn(1, 1)
Z_test, linear_cache_test = linear_forward(A_prev_test, W_test, b_test)
_, activation_cache_test = sigmoid(Z_test)
cache_test = (linear_cache_test, activation_cache_test)

dA_prev, dW, db = linear_activation_backward(dA_test, cache_test, activation="sigmoid")
print("sigmoid:")
print("dA_prev = " + str(dA_prev))
print("dW = " + str(dW))
print("db = " + str(db))

dZ_expected = sigmoid_backward(dA_test, activation_cache_test)
dA_prev_expected, dW_expected, db_expected = linear_backward(dZ_expected, linear_cache_test)
assert np.allclose(dA_prev, dA_prev_expected)
assert np.allclose(dW, dW_expected)
assert np.allclose(db, db_expected)

print("\033[90m\nTest Case 2: relu\n")
_, activation_cache_relu = relu(Z_test)
cache_relu = (linear_cache_test, activation_cache_relu)
dA_prev_r, dW_r, db_r = linear_activation_backward(dA_test, cache_relu, activation="relu")
print("relu:")
print("dA_prev = " + str(dA_prev_r))
print("dW = " + str(dW_r))
print("db = " + str(db_r))

dZ_expected_r = relu_backward(dA_test, activation_cache_relu)
dA_prev_expected_r, dW_expected_r, db_expected_r = linear_backward(dZ_expected_r, linear_cache_test)
assert np.allclose(dA_prev_r, dA_prev_expected_r)
assert np.allclose(dW_r, dW_expected_r)
assert np.allclose(db_r, db_expected_r)

print("\nAll tests passed.")

Test Case 1: sigmoid

sigmoid:
dA_prev = [[ 0.00068794  0.01347576]
 [ 0.00059109  0.01157856]
 [-0.00035859 -0.00702419]]
dW = [[-0.00975201  0.00594401  0.00776748]]
db = [[-0.00669392]]

Test Case 2: relu

relu:
dA_prev = [[ 0.44090989  0.05952761]
 [ 0.37883606  0.05114697]
 [-0.2298228  -0.03102857]]
dW = [[ 0.39899183  0.3973954  -0.06975568]]
db = [[-0.23651234]]

All tests passed.


In [23]:
# GRADED FUNCTION: L_model_backward

def L_model_backward(AL, Y, caches):
    """
    Implement the backward propagation for the [LINEAR->RELU] * (L-1) -> LINEAR -> SIGMOID group
    
    Arguments:
    AL -- probability vector, output of the forward propagation (L_model_forward())
    Y -- true "label" vector (containing 0 if non-cat, 1 if cat)
    caches -- list of caches containing:
                every cache of linear_activation_forward() with "relu" (it's caches[l], for l in range(L-1) i.e l = 0...L-2)
                the cache of linear_activation_forward() with "sigmoid" (it's caches[L-1])
    
    Returns:
    grads -- A dictionary with the gradients
             grads["dA" + str(l)] = ... 
             grads["dW" + str(l)] = ...
             grads["db" + str(l)] = ... 
    """
    grads = {}
    L = len(caches) # the number of layers
    m = AL.shape[1]
    Y = Y.reshape(AL.shape) # after this line, Y is the same shape as AL
    
    # Initializing the backpropagation
    #(1 line of code)
    # dAL = ...
    # YOUR CODE STARTS HERE
    dAL = - (np.divide(Y, AL) - np.divide(1 - Y, 1 - AL))
    
    # YOUR CODE ENDS HERE
    
    # Lth layer (SIGMOID -> LINEAR) gradients. Inputs: "dAL, current_cache". Outputs: "grads["dAL-1"], grads["dWL"], grads["dbL"]
    #(approx. 5 lines)
    # current_cache = ...
    # dA_prev_temp, dW_temp, db_temp = ...
    # grads["dA" + str(L-1)] = ...
    # grads["dW" + str(L)] = ...
    # grads["db" + str(L)] = ...
    # YOUR CODE STARTS HERE
    current_cache = caches[L - 1]
    dA_prev_temp, dW_temp, db_temp = linear_activation_backward(dAL, current_cache, activation="sigmoid")
    grads["dA" + str(L - 1)] = dA_prev_temp
    grads["dW" + str(L)] = dW_temp
    grads["db" + str(L)] = db_temp
    
    # YOUR CODE ENDS HERE
    
    # Loop from l=L-2 to l=0
    for l in reversed(range(L-1)):
        # lth layer: (RELU -> LINEAR) gradients.
        # Inputs: "grads["dA" + str(l + 1)], current_cache". Outputs: "grads["dA" + str(l)] , grads["dW" + str(l + 1)] , grads["db" + str(l + 1)] 
        #(approx. 5 lines)
        # current_cache = ...
        # dA_prev_temp, dW_temp, db_temp = ...
        # grads["dA" + str(l)] = ...
        # grads["dW" + str(l + 1)] = ...
        # grads["db" + str(l + 1)] = ...
        # YOUR CODE STARTS HERE
        current_cache = caches[l]
    dA_prev_temp, dW_temp, db_temp = linear_activation_backward(grads["dA" + str(l + 1)], current_cache, activation="relu")
    grads["dA" + str(l)] = dA_prev_temp
    grads["dW" + str(l + 1)] = dW_temp
    grads["db" + str(l + 1)] = db_temp
        
        # YOUR CODE ENDS HERE

    return grads

In [24]:
print("Test Case 1:\n")
np.random.seed(3)
AL_test = np.random.randn(1, 2)
Y_test = np.array([[1, 0]])

A0 = np.random.randn(4, 2)
W1 = np.random.randn(3, 4)
b1 = np.random.randn(3, 1)
Z1, linear_cache1 = linear_forward(A0, W1, b1)
A1, activation_cache1 = relu(Z1)

W2 = np.random.randn(1, 3)
b2 = np.random.randn(1, 1)
Z2, linear_cache2 = linear_forward(A1, W2, b2)
A2, activation_cache2 = sigmoid(Z2)

caches_test = [(linear_cache1, activation_cache1), (linear_cache2, activation_cache2)]

grads = L_model_backward(AL_test, Y_test, caches_test)

print("dW1 = " + str(grads["dW1"]))
print("db1 = " + str(grads["db1"]))
print("dA0 = " + str(grads["dA0"]))

expected_keys = {"dA0", "dW1", "db1", "dA1", "dW2", "db2"}
assert expected_keys.issubset(grads.keys())
assert grads["dW1"].shape == W1.shape
assert grads["db1"].shape == b1.shape
assert grads["dA0"].shape == A0.shape
assert grads["dW2"].shape == W2.shape
assert grads["db2"].shape == b2.shape

print("\nAll tests passed.")

Test Case 1:

dW1 = [[ 0.17709232  0.02303542  0.05542585  0.04287697]
 [-0.15529752 -0.02020045 -0.04860458 -0.03760009]
 [ 0.         -0.         -0.         -0.        ]]
db1 = [[-0.05705845]
 [ 0.05003625]
 [ 0.        ]]
dA0 = [[-0.0980409   0.25298205]
 [ 0.08950258 -0.23095002]
 [ 0.09817229 -0.2533211 ]
 [ 0.22137248 -0.5712235 ]]

All tests passed.


In [25]:
# GRADED FUNCTION: update_parameters

def update_parameters(params, grads, learning_rate):
    """
    Update parameters using gradient descent
    
    Arguments:
    params -- python dictionary containing your parameters 
    grads -- python dictionary containing your gradients, output of L_model_backward
    
    Returns:
    parameters -- python dictionary containing your updated parameters 
                  parameters["W" + str(l)] = ... 
                  parameters["b" + str(l)] = ...
    """
    parameters = copy.deepcopy(params)
    L = len(parameters) // 2 # number of layers in the neural network

    # Update rule for each parameter. Use a for loop.
    #(≈ 2 lines of code)
    for l in range(L):
        # parameters["W" + str(l+1)] = ...
        # parameters["b" + str(l+1)] = ...
        # YOUR CODE STARTS HERE
        parameters["W" + str(l+1)] = parameters["W" + str(l+1)] - learning_rate * grads["dW" + str(l+1)]
        parameters["b" + str(l+1)] = parameters["b" + str(l+1)] - learning_rate * grads["db" + str(l+1)]
        
        # YOUR CODE ENDS HERE
    return parameters

In [26]:
print("Test Case 1:\n")
np.random.seed(2)
W1 = np.random.randn(3, 4)
b1 = np.random.randn(3, 1)
W2 = np.random.randn(1, 3)
b2 = np.random.randn(1, 1)
parameters_test = {"W1": W1, "b1": b1, "W2": W2, "b2": b2}

np.random.seed(3)
dW1 = np.random.randn(3, 4)
db1 = np.random.randn(3, 1)
dW2 = np.random.randn(1, 3)
db2 = np.random.randn(1, 1)
grads_test = {"dW1": dW1, "db1": db1, "dW2": dW2, "db2": db2}

learning_rate = 0.1
updated_parameters = update_parameters(parameters_test, grads_test, learning_rate)

print("W1 = " + str(updated_parameters["W1"]))
print("b1 = " + str(updated_parameters["b1"]))
print("W2 = " + str(updated_parameters["W2"]))
print("b2 = " + str(updated_parameters["b2"]))

assert np.allclose(updated_parameters["W1"], W1 - learning_rate * dW1)
assert np.allclose(updated_parameters["b1"], b1 - learning_rate * db1)
assert np.allclose(updated_parameters["W2"], W2 - learning_rate * dW2)
assert np.allclose(updated_parameters["b2"], b2 - learning_rate * db2)

# Orijinal parametreler bozulmamış olmalı (deepcopy sayesinde)
assert np.allclose(parameters_test["W1"], W1)

print("\nAll tests passed.")

Test Case 1:

W1 = [[-0.59562069 -0.09991781 -2.14584584  1.82662008]
 [-1.76569676 -0.80627147  0.51115557 -1.18258802]
 [-1.0535704  -0.86128581  0.68284052  2.20374577]]
b1 = [[-0.04659241]
 [-1.28888275]
 [ 0.53405496]]
W2 = [[-0.55569196  0.0354055   1.32964895]]
b2 = [[-0.84610769]]

All tests passed.
